env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eol-last:
    - error
    - always
  no-var:
    - warn
  prefer-const:
    - warn
    - destructuring: all
